### ISSUE TITLE
Run django withou compose

### ISSUE THREAD

**Issue by juanbenitopr** [atbaker/docker-django#1]
The first part of exercise says run the django container without the compose up, but if you want to run it you need to start the postgres and memcached service too, then you will recive an error. If you want to solve it, you have to comment the lines about postgre and memcached in config/docker.py.

**Comment by atbaker** [comment]
Hey @juanbenitopr - thanks for the issue.

This tutorial is pretty old now. I should put a big notice on it that says there are probably better Docker tutorials out there now.

I can't think of a specific one off the top of my head, but because Docker evolves so quickly, I might try googling "docker tutorial" but then restrict your results to only pages updated in the past year.

Thanks!
